import { Offer } from "../types/Offer";


export const offersList: Offer[] = [
    {
      images: [],
      title: "Red Giant Bike",
      description: "Red Giant Bike",
      price: 2000,
      date: "16-07-2023",
      author: "John",
      place: "USA",
      phone: "888 900 900",
      category: "Cars",
    },
    {
      images: [],
      title: "Luxury House",
      description: "Luxury House",
      price: 70000000,
      date: "16-07-2023",
      author: "John",
      place: "USA",
      phone: "888 900 900",
      category: "Cars",
    },
    {
      images: [],
      title: "Used 2018 Lexus LS",
      description: "Used 2018 Lexus LS",
      price: 65000,
      date: "16-07-2023",
      author: "John",
      place: "USA",
      phone: "888 900 900",
      category: "Cars",
    },
    {
      images: [],
      title: "Mercedes S class",
      description: "Mercedes S class",
      price: 70000,
      date: "16-07-2023",
      author: "John",
      place: "USA",
      phone: "888 900 900",
      category: "Cars",
    },
    {
      images: [],
      title: "iPhone 14 Pro mini",
      description: "iPhone 14 Pro mini",
      price: 1000,
      date: "16-07-2023",
      author: "John",
      place: "USA",
      phone: "888 900 900",
      category: "Cars",
    },
    {
      images: [],
      title: "Macbook air 2 pro",
      description: "Macbook air 2 pro",
      price: 2000,
      date: "16-07-2023",
      author: "John",
      place: "USA",
      phone: "888 900 900",
      category: "Cars",
    },
    {
      images: [],
      title: "Handmade chess set",
      description: "Handmade chess set",
      price: 450,
      date: "16-07-2023",
      author: "John",
      place: "USA",
      phone: "888 900 900",
      category: "Cars",
    },
    {
      images: [],
      title: "Gibson Les Paul",
      description: "Gibson Les Paul",
      price: 2000,
      date: "16-07-2023",
      author: "John",
      place: "USA",
      phone: "888 900 900",
      category: "Cars",
    },
    {
      images: [],
      title: "Running shoes",
      description: "Running shoes",
      price: 200,
      date: "16-07-2023",
      author: "John",
      place: "USA",
      phone: "888 900 900",
      category: "Cars",
    },
    {
      images: [],
      title: "Luxury apartment",
      description: "Luxury apartment",
      price: 400,
      date: "16-07-2023",
      author: "John",
      place: "USA",
      phone: "888 900 900",
      category: "Cars",
    },
    {
      images: [],
      title: "Used Skates",
      description: "Used Skates",
      price: 200,
      date: "16-07-2023",
      author: "John",
      place: "USA",
      phone: "888 900 900",
      category: "Cars",
    },
    {
      images: [],
      title: "Antic chair",
      description: "Antic chair",
      price: 3000,
      date: "16-07-2023",
      author: "John",
      place: "USA",
      phone: "888 900 900",
      category: "Cars",
    },
  ];