import { Offer } from "../types/Offer";

export const offersList: Offer[] = [
  {
    images: [
      "https://drive.google.com/uc?export=view&id=1u6lgyn-QDEiXd58xA1PoCJDrAHHmxrKT",
      "https://drive.google.com/uc?export=view&id=16X6IDhyIGIwGgD_4zprenx9eU1tcjuVl",
      "https://drive.google.com/uc?export=view&id=1pbZP8SJ7VWmHqE8sENYn4FXdM4Svsl_Z",
    ],
    title: "Red Giant Bike",
    description: "Red Giant Bike",
    price: 2000,
    date: "16-07-2023",
    author: "John",
    country: "USA",
    phone: "888 900 900",
    category: "Sport",
  },
  {
    images: [
      "https://drive.google.com/uc?export=view&id=1RPiCdr92VzI9Iy00bF7wPkS9eAJxVnVB",
      "https://drive.google.com/uc?export=view&id=1RBVa-gA-TCXDBNV428Z8RWwC8ZiNMpa3",
      "https://drive.google.com/uc?export=view&id=1bPst08Uqh8-_YR4PN4pLgSRNZZG92u24",
    ],

    title: "Luxury House",
    description: "Luxury House",
    price: 70000000,
    date: "16-07-2023",
    author: "John",
    country: "USA",
    phone: "888 900 900",
    category: "Houses",
  },
  {
    images: [
      "https://drive.google.com/uc?export=view&id=1bMJFS58gKd6n5qYB3w0EePxApZ3JXySI",
      "https://drive.google.com/uc?export=view&id=19DbvDp9Fti0moHgg-ZHxy2ELyULbspYk",
      "https://drive.google.com/uc?export=view&id=1ZIDQNPjsTO-2-iDs_cGDSWcD-woN70X_",
    ],
    title: "Used 2018 Lexus LS",
    description: "Used 2018 Lexus LS",
    price: 85000,
    date: "16-07-2023",
    author: "John",
    country: "USA",
    phone: "888 900 900",
    category: "Cars",
  },
  {
    images: [
      "https://drive.google.com/uc?export=view&id=1rCxMxEbfzfIAuITx0lVFTpvpbwC9oOqx",
      "https://drive.google.com/uc?export=view&id=1r0voii_9J7INHooYEyJ3iyvcMElFlMru",
      "https://drive.google.com/uc?export=view&id=1ZjUnvcPYIuG-nN1VLBcCVE0qJxod_CZr",
    ],
    title: "Mercedes S class",
    description: "Mercedes S class",
    price: 70000,
    date: "16-07-2023",
    author: "John",
    country: "USA",
    phone: "888 900 900",
    category: "Cars",
  },
  {
    images: [
      "https://drive.google.com/uc?export=view&id=1j0XbOlT6VjNdjpO0sQvnBUl2YbiUpFbc",
      "https://drive.google.com/uc?export=view&id=1xQE_1NX9c_jjB5HyoELPsBlDHGjO_p7T",
      "https://drive.google.com/uc?export=view&id=1g740EEoiTJX52eFq_wbL8gyZwFKnz_X1",
    ],
    title: "iPhone 14 Pro mini",
    description: "iPhone 14 Pro mini",
    price: 1000,
    date: "16-07-2023",
    author: "John",
    country: "USA",
    phone: "888 900 900",
    category: "Electronics",
  },
  {
    images: [
      "https://drive.google.com/uc?export=view&id=1t42gywAfYYDpJuOmlnNulSBjX7yCZ_o9",
      "https://drive.google.com/uc?export=view&id=1b2q7KeA_icGeuiMsVd_b65PRoBwTc-OS",
      "https://drive.google.com/uc?export=view&id=1zDuuezusgaqD9O-8rvofBgJewPSTXthv",
    ],
    title: "Macbook air 2 pro",
    description: "Macbook air 2 pro",
    price: 2000,
    date: "16-07-2023",
    author: "John",
    country: "USA",
    phone: "888 900 900",
    category: "Electronics",
  },
  {
    images: [
      "https://drive.google.com/uc?export=view&id=1UMRRpeBiLDzlXpWMDkp9gZnPSuZV_X0q",
      "https://drive.google.com/uc?export=view&id=1eHugTBOkY9luhRGD0a_GY8NW5BPohxAF",
      "https://drive.google.com/uc?export=view&id=1rQDgYS5s-XDwiNazVEJJma2fBi1kNTdQ",
    ],
    title: "Handmade chess set",
    description: "Handmade chess set",
    price: 450,
    date: "16-07-2023",
    author: "John",
    country: "USA",
    phone: "888 900 900",
    category: "Hobby",
  },
  {
    images: [
      "https://drive.google.com/uc?export=view&id=1wKn9RBjYXSdKSGPwQCoGXI6VBNaOzU36",
      "https://drive.google.com/uc?export=view&id=1HH_kPWkXYnY7fYrrulgu_8r8HWL4hNe_",
      "https://drive.google.com/uc?export=view&id=1HgZ6tDvr-KDy9bnIeJnEaDQ2uW7rCsMo",
    ],
    title: "Gibson Les Paul",
    description: "Gibson Les Paul",
    price: 2000,
    date: "16-07-2023",
    author: "John",
    country: "USA",
    phone: "888 900 900",
    category: "Hobby",
  },
  {
    images: [
      "https://drive.google.com/uc?export=view&id=1BR5dq1GwuHe__wbC0ioq51vIbsZFnGmt",
      "https://drive.google.com/uc?export=view&id=19H0ikrnb8R7adMWmLbEOf3rm1Ojbhv3u",
      "https://drive.google.com/uc?export=view&id=1gW3Y555eTltUKfXtE5Zk1CeOzoHUQMh_",
    ],
    title: "Running shoes",
    description: "Running shoes",
    price: 200,
    date: "16-07-2023",
    author: "John",
    country: "USA",
    phone: "888 900 900",
    category: "Sport",
  },
  // {
  //   images: [],
  //   title: "Luxury apartment",
  //   description: "Luxury apartment",
  //   price: 400,
  //   date: "16-07-2023",
  //   author: "John",
  //   country: "USA",
  //   phone: "888 900 900",
  //   category: "Hotels",
  // },
  // {
  //   images: [],
  //   title: "Used Skates",
  //   description: "Used Skates",
  //   price: 200,
  //   date: "16-07-2023",
  //   author: "John",
  //   country: "USA",
  //   phone: "888 900 900",
  //   category: "Hobby",
  // },
  // {
  //   images: [],
  //   title: "Antic chair",
  //   description: "Antic chair",
  //   price: 3000,
  //   date: "16-07-2023",
  //   author: "John",
  //   country: "USA",
  //   phone: "888 900 900",
  //   category: "Furnitures",
  // },
];
