import { Offer } from "../types/Types";

export const offersList: Offer[] = [
  {
    id: 1,
    images: [
      "https://i.postimg.cc/G3sw-ckqd/image3.jpg",
      "https://i.postimg.cc/Qdzrq0M9/image4.jpg",
      "https://i.postimg.cc/T1bZC6pp/image1.jpg",
      "https://i.postimg.cc/yY4qWkb9/image2.jpg",
    ],
    title: "Red Giant Bike",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure consequatur, vero facilis suscipit mollitia architecto explicabo aut accusamus beatae nostrum at Lorem ipsum dolor, sit amet consectetur adipisicing elit. Corrupti quo, unde natus voluptatum similique accusamus nihil ipsa, consequuntur praesentium assumenda sunt iure veritatis animi eum sint? Itaque delectus voluptatum quos optio voluptatem eius possimus quibusdam. ",
    price: 2000,
    date: "16-07-2023",
    author: "John",
    country: "USA",
    phone: "888 900 900",
    category: "Sport",
  },
  {
    id: 2,
    images: [
      "https://i.postimg.cc/Tw6mpjgF/image1.jpg",
      "https://i.postimg.cc/nrdQR6gf/image2.jpg",
      "https://i.postimg.cc/D0fXc2Cc/image3.jpg",
    ],

    title: "Luxury House",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure consequatur, vero facilis suscipit mollitia architecto explicabo aut accusamus beatae nostrum at Lorem ipsum dolor, sit amet consectetur adipisicing elit. Corrupti quo, unde natus voluptatum similique accusamus nihil ipsa, consequuntur praesentium assumenda sunt iure veritatis animi eum sint? Itaque delectus voluptatum quos optio voluptatem eius possimus quibusdam.",
    price: 7000000,
    date: "16-07-2023",
    author: "John",
    country: "USA",
    phone: "888 900 900",
    category: "Houses",
  },
  {
    id: 3,
    images: [
      "https://i.postimg.cc/pLjpzhWH/image1.jpg",
      "https://i.postimg.cc/Dzd0p94p/image2.jpg",
      "https://i.postimg.cc/R0zqRShn/image3.png",
    ],
    title: "2018 Lexus LS",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure consequatur, vero facilis suscipit mollitia architecto explicabo aut accusamus beatae nostrum at Lorem ipsum dolor, sit amet consectetur adipisicing elit. Corrupti quo, unde natus voluptatum similique accusamus nihil ipsa, consequuntur praesentium assumenda sunt iure veritatis animi eum sint? Itaque delectus voluptatum quos optio voluptatem eius possimus quibusdam.",
    price: 85000,
    date: "16-07-2023",
    author: "John",
    country: "USA",
    phone: "888 900 900",
    category: "Cars",
  },
  {
    id: 4,
    images: [
      "https://i.postimg.cc/dVGVDb6Q/image2.jpg",
      "https://i.postimg.cc/4ND3ffzF/image1.jpg",
      "https://i.postimg.cc/nLZcm3S4/image3.jpg",
    ],
    title: "Mercedes S class",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure consequatur, vero facilis suscipit mollitia architecto explicabo aut accusamus beatae nostrum at Lorem ipsum dolor, sit amet consectetur adipisicing elit. Corrupti quo, unde natus voluptatum similique accusamus nihil ipsa, consequuntur praesentium assumenda sunt iure veritatis animi eum sint? Itaque delectus voluptatum quos optio voluptatem eius possimus quibusdam.",
    price: 70000,
    date: "16-07-2023",
    author: "John",
    country: "USA",
    phone: "888 900 900",
    category: "Cars",
  },
  {
    id: 5,
    images: [
      "https://i.postimg.cc/pL5qjZ5L/image2.jpg",
      "https://i.postimg.cc/2jTcN3fr/image1.jpg",
      "https://i.postimg.cc/3RYBPQSk/image3.jpg",
    ],
    title: "iPhone 14 Pro mini",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure consequatur, vero facilis suscipit mollitia architecto explicabo aut accusamus beatae nostrum at Lorem ipsum dolor, sit amet consectetur adipisicing elit. Corrupti quo, unde natus voluptatum similique accusamus nihil ipsa, consequuntur praesentium assumenda sunt iure veritatis animi eum sint? Itaque delectus voluptatum quos optio voluptatem eius possimus quibusdam.",
    price: 1000,
    date: "16-07-2023",
    author: "John",
    country: "USA",
    phone: "888 900 900",
    category: "Electronics",
  },
  {
    id: 6,
    images: [
      "https://i.postimg.cc/k4S2F2F8/image1.jpg",
      "https://i.postimg.cc/HsdrXsJc/image2.jpg",
      "https://i.postimg.cc/T3hYJyTw/image3.jpg",
    ],
    title: "Macbook air 2 pro",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure consequatur, vero facilis suscipit mollitia architecto explicabo aut accusamus beatae nostrum at Lorem ipsum dolor, sit amet consectetur adipisicing elit. Corrupti quo, unde natus voluptatum similique accusamus nihil ipsa, consequuntur praesentium assumenda sunt iure veritatis animi eum sint? Itaque delectus voluptatum quos optio voluptatem eius possimus quibusdam.",
    price: 2000,
    date: "16-07-2023",
    author: "John",
    country: "USA",
    phone: "888 900 900",
    category: "Electronics",
  },
  {
    id: 7,
    images: [
      "https://i.postimg.cc/J7992G30/image1.jpg",
      "https://i.postimg.cc/gk8fFm4D/image2.jpg",
      "https://i.postimg.cc/3wJ6vphS/image3.jpg",
    ],
    title: "Handmade chess set",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure consequatur, vero facilis suscipit mollitia architecto explicabo aut accusamus beatae nostrum at Lorem ipsum dolor, sit amet consectetur adipisicing elit. Corrupti quo, unde natus voluptatum similique accusamus nihil ipsa, consequuntur praesentium assumenda sunt iure veritatis animi eum sint? Itaque delectus voluptatum quos optio voluptatem eius possimus quibusdam.",
    price: 450,
    date: "16-07-2023",
    author: "John",
    country: "USA",
    phone: "888 900 900",
    category: "Hobby",
  },
  {
    id: 8,
    images: [
      "https://i.postimg.cc/5NdRmD1F/image1.jpg",
      "https://i.postimg.cc/x19pwHXf/image2.jpg",
      "https://i.postimg.cc/hPL3ZMPZ/image3.jpg",
    ],
    title: "Gibson Les Paul",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure consequatur, vero facilis suscipit mollitia architecto explicabo aut accusamus beatae nostrum at Lorem ipsum dolor, sit amet consectetur adipisicing elit. Corrupti quo, unde natus voluptatum similique accusamus nihil ipsa, consequuntur praesentium assumenda sunt iure veritatis animi eum sint? Itaque delectus voluptatum quos optio voluptatem eius possimus quibusdam. ",
    price: 2000,
    date: "16-07-2023",
    author: "John",
    country: "USA",
    phone: "888 900 900",
    category: "Hobby",
  },
  {
    id: 9,
    images: [
      "https://i.postimg.cc/t4rk8c0k/image1.jpg",
      "https://i.postimg.cc/bvWTw2w2/image2.jpg",
      "https://i.postimg.cc/B6FCLQj7/image3.jpg",
    ],
    title: "Running shoes",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure consequatur, vero facilis suscipit mollitia architecto explicabo aut accusamus beatae nostrum at Lorem ipsum dolor, sit amet consectetur adipisicing elit. Corrupti quo, unde natus voluptatum similique accusamus nihil ipsa, consequuntur praesentium assumenda sunt iure veritatis animi eum sint? Itaque delectus voluptatum quos optio voluptatem eius possimus quibusdam.",
    price: 200,
    date: "16-07-2023",
    author: "John",
    country: "USA",
    phone: "888 900 900",
    category: "Sport",
  },
  // 
  {
    id: 10,
    images: ["https://i.postimg.cc/bJkC7SFY/image1.jpg", "https://i.postimg.cc/rs9hmXkv/image3.jpg", "https://i.postimg.cc/gjpSmcfV/image2.jpg"],
    title: "Used headphones",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure consequatur, vero facilis suscipit mollitia architecto explicabo aut accusamus beatae nostrum at Lorem ipsum dolor, sit amet consectetur adipisicing elit. Corrupti quo, unde natus voluptatum similique accusamus nihil ipsa, consequuntur praesentium assumenda sunt iure veritatis animi eum sint? Itaque delectus voluptatum quos optio voluptatem eius possimus quibusdam.",
    price: 200,
    date: "16-07-2023",
    author: "John",
    country: "USA",
    phone: "888 900 900",
    category: "Electronics",
  },
  {
    id: 11,
    images: ["https://i.postimg.cc/qvvFNRgQ/image1.jpg", "https://i.postimg.cc/N0yPxz6H/image2.jpg"],
    title: "Antic chair",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure consequatur, vero facilis suscipit mollitia architecto explicabo aut accusamus beatae nostrum at Lorem ipsum dolor, sit amet consectetur adipisicing elit. Corrupti quo, unde natus voluptatum similique accusamus nihil ipsa, consequuntur praesentium assumenda sunt iure veritatis animi eum sint? Itaque delectus voluptatum quos optio voluptatem eius possimus quibusdam.",
    price: 3000,
    date: "16-07-2023",
    author: "John",
    country: "USA",
    phone: "888 900 900",
    category: "Furnitures",
  },
  {
    id: 12,
    images: ["https://i.postimg.cc/jdZgYbvf/image1.jpg", "https://i.postimg.cc/W1z92HfH/image2.jpg", "https://i.postimg.cc/yNSvRSKh/image3.jpg"],
    title: "LCD TV",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure consequatur, vero facilis suscipit mollitia architecto explicabo aut accusamus beatae nostrum at Lorem ipsum dolor, sit amet consectetur adipisicing elit. Corrupti quo, unde natus voluptatum similique accusamus nihil ipsa, consequuntur praesentium assumenda sunt iure veritatis animi eum sint? Itaque delectus voluptatum quos optio voluptatem eius possimus quibusdam.",
    price: 1000,
    date: "16-07-2023",
    author: "John",
    country: "USA",
    phone: "888 900 900",
    category: "Electronics",
  },
  {
    id: 13,
    images: [ "https://i.postimg.cc/qqQLrscr/image2.jpg", "https://i.postimg.cc/D07gRjX5/image1.jpg","https://i.postimg.cc/bYRL1h75/image3.jpg"],
    title: "Leather bag",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure consequatur, vero facilis suscipit mollitia architecto explicabo aut accusamus beatae nostrum at Lorem ipsum dolor, sit amet consectetur adipisicing elit. Corrupti quo, unde natus voluptatum similique accusamus nihil ipsa, consequuntur praesentium assumenda sunt iure veritatis animi eum sint? Itaque delectus voluptatum quos optio voluptatem eius possimus quibusdam.",
    price: 300,
    date: "16-07-2023",
    author: "John",
    country: "USA",
    phone: "888 900 900",
    category: "Clothes",
  },
  // {
    //   id: 14,
    //   images: ["https://i.postimg.cc/26LRV5cg/image1.jpg", "https://i.postimg.cc/jdb0Stzk/image2.jpg", "https://i.postimg.cc/PfZnHP8w/image3.jpg"],
    //   title: "Luxury apartment",
    //   description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure consequatur, vero facilis suscipit mollitia architecto explicabo aut accusamus beatae nostrum at Lorem ipsum dolor, sit amet consectetur adipisicing elit. Corrupti quo, unde natus voluptatum similique accusamus nihil ipsa, consequuntur praesentium assumenda sunt iure veritatis animi eum sint? Itaque delectus voluptatum quos optio voluptatem eius possimus quibusdam.",
    //   price: 400,
    //   date: "16-07-2023",
    //   author: "John",
    //   country: "USA",
    //   phone: "888 900 900",
    //   category: "Hotels",
    // },
];
