INSERT INTO offers (images, title, description, price, date, author, country, phone, category) VALUES (array['https://i.postimg.cc/J7992G30/image1.jpg', 'https://i.postimg.cc/gk8fFm4D/image2.jpg', 'https://i.postimg.cc/3wJ6vphS/image3.jpg'], 'Handmade chess set', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure consequatur, vero facilis suscipit mollitia architecto explicabo aut accusamus beatae nostrum at Lorem ipsum dolor, sit amet consectetur adipisicing elit. Corrupti quo, unde natus voluptatum similique accusamus nihil ipsa, consequuntur praesentium assumenda sunt iure veritatis animi eum sint? Itaque delectus voluptatum quos optio voluptatem eius possimus quibusdam.', 450, '16-07-2023', 'John', 'USA', '888 900 900', 'Hobby');

INSERT INTO offers (images, title, description, price, date, author, country, phone, category) VALUES (array['https://i.postimg.cc/k4S2F2F8/image1.jpg', 'https://i.postimg.cc/HsdrXsJc/image2.jpg', 'https://i.postimg.cc/T3hYJyTw/image3.jpg'], 'Macbook air 2 pro', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure consequatur, vero facilis suscipit mollitia architecto explicabo aut accusamus beatae nostrum at Lorem ipsum dolor, sit amet consectetur adipisicing elit. Corrupti quo, unde natus voluptatum similique accusamus nihil ipsa, consequuntur praesentium assumenda sunt iure veritatis animi eum sint? Itaque delectus voluptatum quos optio voluptatem eius possimus quibusdam.', 2000, '16-07-2023', 'John', 'USA', '888 900 900', 'Electronics');

INSERT INTO offers (images, title, description, price, date, author, country, phone, category) VALUES (array['https://i.postimg.cc/5NdRmD1F/image1.jpg', 'https://i.postimg.cc/x19pwHXf/image2.jpg', 'https://i.postimg.cc/hPL3ZMPZ/image3.jpg'], 'Gibson Les Paul', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure consequatur, vero facilis suscipit mollitia architecto explicabo aut accusamus beatae nostrum at Lorem ipsum dolor, sit amet consectetur adipisicing elit. Corrupti quo, unde natus voluptatum similique accusamus nihil ipsa, consequuntur praesentium assumenda sunt iure veritatis animi eum sint? Itaque delectus voluptatum quos optio voluptatem eius possimus quibusdam.', 2000, '16-07-2023', 'John', 'USA', '888 900 900', 'Hobby');

INSERT INTO offers (images, title, description, price, date, author, country, phone, category) VALUES (array['https://i.postimg.cc/t4rk8c0k/image1.jpg', 'https://i.postimg.cc/bvWTw2w2/image2.jpg', 'https://i.postimg.cc/B6FCLQj7/image3.jpg'], 'Running shoes', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure consequatur, vero facilis suscipit mollitia architecto explicabo aut accusamus beatae nostrum at Lorem ipsum dolor, sit amet consectetur adipisicing elit. Corrupti quo, unde natus voluptatum similique accusamus nihil ipsa, consequuntur praesentium assumenda sunt iure veritatis animi eum sint? Itaque delectus voluptatum quos optio voluptatem eius possimus quibusdam.', 200, '16-07-2023', 'John', 'USA', '888 900 900', 'Sport');

INSERT INTO offers (images, title, description, price, date, author, country, phone, category) VALUES (array['https://i.postimg.cc/bJkC7SFY/image1.jpg', 'https://i.postimg.cc/rs9hmXkv/image3.jpg', 'https://i.postimg.cc/gjpSmcfV/image2.jpg'], 'Used headphones', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure consequatur, vero facilis suscipit mollitia architecto explicabo aut accusamus beatae nostrum at Lorem ipsum dolor, sit amet consectetur adipisicing elit. Corrupti quo, unde natus voluptatum similique accusamus nihil ipsa, consequuntur praesentium assumenda sunt iure veritatis animi eum sint? Itaque delectus voluptatum quos optio voluptatem eius possimus quibusdam.', 200, '16-07-2023', 'John', 'USA', '888 900 900', 'Electronics');

INSERT INTO offers (images, title, description, price, date, author, country, phone, category) VALUES (array['https://i.postimg.cc/qvvFNRgQ/image1.jpg', 'https://i.postimg.cc/N0yPxz6H/image2.jpg'], 'Antic chair', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure consequatur, vero facilis suscipit mollitia architecto explicabo aut accusamus beatae nostrum at Lorem ipsum dolor, sit amet consectetur adipisicing elit. Corrupti quo, unde natus voluptatum similique accusamus nihil ipsa, consequuntur praesentium assumenda sunt iure veritatis animi eum sint? Itaque delectus voluptatum quos optio voluptatem eius possimus quibusdam.', 3000, '16-07-2023', 'John', 'USA', '888 900 900', 'Furnitures');

INSERT INTO offers (images, title, description, price, date, author, country, phone, category) VALUES (array['https://i.postimg.cc/yNSvRSKh/image3.jpg', 'https://i.postimg.cc/jdZgYbvf/image1.jpg', 'https://i.postimg.cc/W1z92HfH/image2.jpg'], 'LCD TV', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure consequatur, vero facilis suscipit mollitia architecto explicabo aut accusamus beatae nostrum at Lorem ipsum dolor, sit amet consectetur adipisicing elit. Corrupti quo, unde natus voluptatum similique accusamus nihil ipsa, consequuntur praesentium assumenda sunt iure veritatis animi eum sint? Itaque delectus voluptatum quos optio voluptatem eius possimus quibusdam.', 1000, '16-07-2023', 'John', 'USA', '888 900 900', 'Electronics');